name: Build and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Copy .htaccess
        run: cp static/.htaccess build/
        
      - name: Set Permissions
        run: chmod -R 755 build/

      - name: Debug Build Directory
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "Content of build/index.html:"
          cat build/index.html

      - name: Clean Remote Directory
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './empty/'
          remote_path: '/customers/1/0/6/napkin-ops.com/httpd.www'
          sftp_only: true
          delete_remote_files: true
          
      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './build/'
          remote_path: '/customers/1/0/6/napkin-ops.com/httpd.www'
          sftp_only: true